require 'test/unit'
require 'tc_webdav_basic.rb'
require 'tc_webdav_publish.rb'
require 'tc_dav-cat.rb'
# require 'tc_dav-cd.rb'
require 'tc_dav-cp.rb'
require 'tc_dav-delete.rb'
# require 'tc_dav-ls.rb'
require 'tc_dav-mkcol.rb'
require 'tc_dav-mv.rb'
require 'tc_dav-propfind.rb'
require 'tc_property_file.rb'
